[build]
target = ["x86_64-unknown-linux-gnu"]
rustflags = "-Zlocation-detail=none -C link-arg=-nostartfiles -C link-arg=-nostdlib"

[unstable]
build-std = ["core"]
build-std-features= ["panic_immediate_abort"]
